job_log_dir:
- /home/rgarciap/logs
conda_dir:
- /scratch/artemis/rgarciap/miniconda3
conda_env_name:
- base
job_type_0:
- besteffort
job_type_1:
- idempotent
walltime:
- "48:00:00"
n_nodes:
- 1
n_cpus:
- 10
